#!/usr/bin/env sh

set -e

echo 'Building Docs 🚀'

# Services
node ./scripts/typedocs/index.js build src/services/auth/index.js --repo https://github.com/soulfresh/react-website-template/tree/master
node ./scripts/typedocs/index.js build src/services/graphql-utils/index.js --repo https://github.com/soulfresh/react-website-template/tree/master
node ./scripts/typedocs/index.js build src/services/graphql-utils/mocks/index.js --repo https://github.com/soulfresh/react-website-template/tree/master
node ./scripts/typedocs/index.js build src/services/example-graphql-service/index.js --repo https://github.com/soulfresh/react-website-template/tree/master
node ./scripts/typedocs/index.js build src/services/example-graphql-service/mocks/index.js --repo https://github.com/soulfresh/react-website-template/tree/master

# Testing
node ./scripts/typedocs/index.js build src/test/index.js --repo https://github.com/soulfresh/react-website-template/tree/master

# SASS utilities
npx sassdoc2md ./src/_utils.scss > ./src/docs/SASS_Utils.md
